### ISSUE TITLE
Rewrite the existing code to use streams.

### ISSUE THREAD

**Issue by leegao** [FloooD/custom_cs2dsrv#12]
As per uprate6's suggestion, I'll probably be able to do this fairly quickly as the migration from the existing codebase shouldn't be much of a problem. Current stream implementation should run about as quickly as if not more efficient than the old implementation since packets are (theoretically) sent in little endian, a cast to the respective datatypes would suffice (except for readline). IE:

```
i = "xfexf3"; // 0xf3fe in LE
short c = *(short*)i; (Returns 0xf3fe, which is correct)
```

I'll be working on this in the experimental branch, as soon as I finish rerouting everything into the scheduler.

**Comment by leegao** [comment]
Committed auxiliary functions into master

**Comment by FloooD** [comment]
eh.. ok i'll look at it tomorrow ;p

**Comment by leegao** [comment]
I'm already working on it, the way that the sends and the packets are written seems as if they weren't even remotely planned out. Each huge blocks of code can be concisely written in less than 5 lines. Fucking dammit, the way that it was written just makes me want to rage <_<

**Comment by leegao** [comment]
Alright, I've gone through about 70% of the packets and have made the code nearly 100% smaller. This is getting onto my nerves so I'm going to drop this until tomorrow.

**Comment by leegao** [comment]
wow, got the packets part down to only 800 or so lines of code from over 2000... reading through that shit was a pain in the ass.

**Comment by FloooD** [comment]
rofl nice

**Comment by leegao** [comment]
alright, the code's somewhat stable enough to be merged into the upstream so I'm gonna go for it and see if the build breaks (shouldn't). Don't make any commits for the next hour.

**Comment by leegao** [comment]
btw why are x/y pointers now? Do they point to the memory of the XY buffer?

**Comment by leegao** [comment]
nvm, didn't look at the commit log
