### ISSUE TITLE
invalid packet client id not synchronized with server

### ISSUE THREAD

**Issue by FloooD** [FloooD/custom_cs2dsrv#18]
I tried joining 127.0.0.1:36963... Got the thing written in the title

don't know if this problem exists for internet or lan cuz I don't have wifi right now (writing from phone :d)

**Comment by leegao** [comment]
yeah, it's in the validatepacket function. It fucks everything up if just one client loses two packets accidentally (you know, as UDP is wont to do). I wanted to delete it but I don't want to break the entire build. I volunteer you to test it out :D

Comment out 
                    //TODO: ValidatePacket fails if client dropped
                    if (ValidatePacket(buffer,id)){ ///Checks and raise the packet numbering if necessary

**Comment by leegao** [comment]
Also, for my sanity's sake, revert back a few builds to see if the same still fails to make sure that it wasn't something that I did :O

**Comment by leegao** [comment]
Also, for reference's sake, this was the original code. I was pretty out of it the day I rewrote this, having just gotten a cold while trying to study for a midterm so I may have made a few mistakes. Plug it back in and see if it still works.

Edit: Also are you on a little endian machine? (IE: what do you get when you compile 
    i=1;printf("%d",_((char_)&i))); 
?)

```
int ValidatePaket(unsigned char *message, int id)
{
    /*
     unsigned short *pTempNummer = malloc(2);
     pTempNummer[0] = message[0];
     pTempNummer[1] = message[1];
     */
    unsigned short *pTempNummer = (unsigned short *) message;
    if (*pTempNummer % 2 != 0)
    {
        if (((*pTempNummer) + 2) < player[id].client_nummer || (*pTempNummer)
                > (player[id].client_nummer + 2))
        {
            printf("Invalid paket! (Bad index: %d; expected: %d)\n", *pTempNummer, player[id].client_nummer);
            //free(pTempNummer);
            return 0;
        }
    }
    if (*pTempNummer - 1 > player[id].client_nummer)
    {
        player[id].client_nummer = *pTempNummer;
    }
    /*
     unsigned short *pNummer = &player[id].client_nummer;
     pNummer[0] = buffer[0];
     pNummer[1] = buffer[1];
     */
    //free(pTempNummer);
    return 1;
}
```

**Comment by FloooD** [comment]
uh i get 1 and i'm too lazy to figure out what that means. my netbook = intel atom + debian 6 32bit + some old gcc version 4.4.2 or something

btw im not gonna be doing too much until next week < spring break :P

**Comment by leegao** [comment]
yeah, 1 is little endian so the code shouldn't break for you and anyone else who's running cs2d (since the packet stream's in LE too). idk, probably either caused by me or was there all along
