### ISSUE TITLE
CFG parser doesn't work.

### ISSUE THREAD

**Issue by leegao** [FloooD/custom_cs2dsrv#2]
It seems that the CFG parser implementation is broken:
1. Data is always terminated with '\n' (original target not posix maybe?)
2. Search name always contains an extra space.

I'll write a patch

**Comment by leegao** [comment]
Screenshot:
http://i.imgur.com/LIw8B.png

Notice how the "sv_name " failed to match "sv_name" and how "Lolz :ASDFASDF\n" has an extra \n

**Comment by FloooD** [comment]
ok now i see why this is in the "experimental" branch xd

**Comment by leegao** [comment]
haha, sorry, had to go to a physics lab, I'm back now, almost done with the CFG parser

**Comment by leegao** [comment]
k, fixed, see last commit in the experimental branch.
