### ISSUE TITLE
cs2d 0119

### ISSUE THREAD

**Issue by FloooD** [FloooD/custom_cs2dsrv#20]
got released yesterday
how the hell do we get the custom server onto the serverlist?

**Comment by leegao** [comment]
bump the version on the return packet, I don't think anything else was changed in the serverlist request

**Comment by leegao** [comment]
I'll wireshark the new protocol once I get back, too lazy to download the new CS2D version <_<

**Comment by FloooD** [comment]
k just installed wireshark and I think I figured it out.. You just need to add some more junk in the player data part of joinroutine_known

btw 'pre_authcode' isn't static in cs2d_dedicated
I can't tell if it even matters to the client

**Comment by FloooD** [comment]
hm wtf i just managed to get all those packets to arrive upside-down...
wait wtf they were upside-down before i touched packets.c lol
https://gist.github.com/893922

line 27-37 are upside-down in custom_cs2dsrv

**Comment by FloooD** [comment]
01:08:33:3a:0b:16:20:23:50:49:00
added that to wtf[] before 3ACK
edit: still doesn't work
edit: nvm i forgot to change the # of bytes copied from wtf to buf
edit: k player can join the server now
