### ISSUE TITLE
windows timers for fps control

### ISSUE THREAD

**Issue by FloooD** [FloooD/custom_cs2dsrv#21]
is there anything other than queryperformancecounter/frequency + Sleep?
the last time i tried the server in windows, fps would go to 32 or 64 or something due to changes in Sleep's resolution (apparently hlds has this problem as well).

**Comment by FloooD** [comment]
http://www.geisswerks.com/ryan/FAQS/timing.html
hm that was pretty interesting

lol windows 98 ftw

**Comment by leegao** [comment]
go go NT platforms

**Comment by FloooD** [comment]
i give up screwed windows.

**Comment by leegao** [comment]
lol, a lowerbound of 30 or 15 ms ping is good enough

**Comment by FloooD** [comment]
ya well 2ms is better xd
