### ISSUE TITLE
Shotgun error: dmg uninitialized

### ISSUE THREAD

**Issue by leegao** [FloooD/custom_cs2dsrv#23]
In script-functions.c
function OnFire

```
case 6:
    dmg == weapons[wpn].weapondamage;
    ...
```

should be changed to

```
case 6:
    dmg = weapons[wpn].weapondamage;
```

else shotgun shots will lead to a segfault

**Comment by FloooD** [comment]
omg fuck i knew i made a retarded mistake somewhere in there lol

**Comment by leegao** [comment]
:P, glad to see that our prodigy's just as sharp as ever
