### ISSUE TITLE
LLVM branch

### ISSUE THREAD

**Issue by leegao** [FloooD/custom_cs2dsrv#29]
Using clang to compile the lua source takes literally a few seconds (2 on my crappy vmware) and generates really really nice error messages. Just leaving this out here in case you want to switch to use llvm as the debug branch.

**Comment by FloooD** [comment]
lolwut vmware
are there any code differences? if it's just 2 more lines in the makefile y dont u just add it to lee_experimental :P

anyway.... i'm totally prepared to bomb one of my midterms :D pass/no-pass grading option ftw

**Comment by leegao** [comment]
lawlz 1 credit?

just wanted to make sure that clang doesn't break on lua, which it didn't, so YAY :D

**Comment by leegao** [comment]
k, patched and merged into lee_experimental

**Comment by FloooD** [comment]
no it's 4 lol fml
taking it for university requirements... u have to choose a class >2 units from a list ;p

anyway i think i just failed that midterm. but i think i got 100 in my quantum midterm :D

**Comment by leegao** [comment]
it's okay, professors tend to be nice towards 15 year old geniuses breaking the curve xD

**Comment by FloooD** [comment]
uh... well if i guessed on 90% of the multiple choice questions they cant rly do much lol
