### ISSUE TITLE
script-functions.c OnBuyAttempt

### ISSUE THREAD

**Issue by FloooD** [FloooD/custom_cs2dsrv#5]
int OnBuyAttempt(int id, int wpnid, int writesocket)
{
    int i;
    for (i = 0; i <= 99; i++)
    {

i can't figure out what that for loop is for...

**Comment by leegao** [comment]
To make sure that we don't hit a null pointer for any weapons (IE: buying a weapon not inside of the weapon table). I changed it to 0xff to make sure that future additions won't break the server (weapon-id being encoded as a byte), but it shouldn't be too big of a deal since only buyable weapons can break right now.

**Comment by FloooD** [comment]
i think u're talking about weapons.c

if u look inside the for-loop you'll see that the "i" isn't used anywhere. so either it's something jermuk forgot to erase in his testing... or i'm just blind.

btw, the 100 nested if statements look disgusting lol.
ill go rewrite it

**Comment by leegao** [comment]
yep, a reference search turned up nothing, the loop is useless

**Comment by FloooD** [comment]
k im almost done with it
btw also making it 1 weapon per slot for slot 1/2

**Comment by FloooD** [comment]
structs are getting me confused
player[1].slot[1].slot = ????????????

**Comment by leegao** [comment]
guess it's just a reference back to the actual slot since we don't hold a reference to the player that currently holds the weapon (maybe we should?) Btw, pushed in the command line argument parser. I'm gonna go to sleep now since I have a midterm tomorrow morning T_T

**Comment by FloooD** [comment]
wups... accidentally commited that to master somehow rofl
gluck on ur midterm ;D
