### ISSUE TITLE
Ambiguous socket identifiers

### ISSUE THREAD

**Issue by leegao** [FloooD/custom_cs2dsrv#7]
Minor: main.c uses readsocket while the rest of the program uses writesocket. However these sockets are passed in irregardless of the read-write state (read state is often flipped into write state mid execution in main) so the naming is really confusing. Should we just rename the readsockets into sock in main.c?

PS: this is already done in the experimental branch, I'll revert if you say no.

**Comment by FloooD** [comment]
go ahead :P

**Comment by leegao** [comment]
k, patched, it's in the pull queue
